export const loginTypes = {
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    CREATE_USER: 'CREATE_USER',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    TOGGLE_LOGIN: 'TOGGLE_LOGIN',
    LOGIN_PHONE: 'LOGIN_PHONE',
    UPDATE_USER: 'UPDATE_USER',
}